name: OpenAPI Client Generation and Deploy pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-petstore-api-client:
    name: petstore
    uses: ./.github/workflows/generate-client-workflow.yml
    with:
      openapi_spec_path: 'supporting-files/oas-input/petstore-api.yaml'
      app_name: petstore-api

  generate-petstore-analyzer-api-client:
    name: petstore analyzer
    uses: ./.github/workflows/generate-client-workflow.yml
    with:
      openapi_spec_path: 'supporting-files/oas-input/petstore-analyzer-api.yaml'
      app_name: petstore-analyzer-api
