name: OpenAPI Client Generation and Deploy pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-petstore-api-client:
    name: petstore
    uses: ./.github/workflows/generate-client-workflow.yml
    with:
      openapi_spec_path: 'supporting-files/oas-input/petstore-api.yaml'
      app_name: 'petstore'
      package_name: 'petstore'
      package_version: '1.0.27'
      github_token: ${{ secrets.MB_PAT }}

  generate-petstore-analyzer-api-client:
    name: petstore analyzer
    uses: ./.github/workflows/generate-client-workflow.yml
    with:
      openapi_spec_path: 'supporting-files/oas-input/petstore-analyzer-api.yaml'
      app_name: 'petstore-analyzer'
      package_name: 'petstore.analyzer'
      package_version: '1.0.0'
      github_token: ${{ secrets.MB_PAT }}
